#!/bin/sh
# the setup script lies here

# parse arguments and create config files
for opt in "$@"
do
  case $opt in
    -bname=*)
      BONDNAME="${opt#*=}"
      shift
      ;;
    -iface1=*)
      INTERFACE1="${opt#*=}"
      shift
      ;;
    -iface2=*)
      INTERFACE2="${opt#*=}"
      shift
      ;;
    *)
      echo "unknown option ${opt}"
      shift
      ;;
  esac
done
 
if [ "${BONDNAME}" = "" ] || [ "${INTERFACE1}" = "" ] || [ "${INTERFACE2}" = "" ] ; then
  echo "Incorrect number of arguments or invalid argument syntax."
  echo "Usage: sudo ./bondsetup.sh -bname=bond_name -iface1=interface_1_name -iface2=interface_2_name"
  exit 1
fi
 
echo "bondname = ${BONDNAME}"
echo "interface 1 = ${INTERFACE1}"
echo "interface 2 = ${INTERFACE2}"
 
# remove bond interfaces from /etc/network/interfaces
echo "`cat /etc/network/interfaces | grep -v ${INTERFACE1}'\|'$INTERFACE2'\|'$BONDNAME'\|source'`" > /etc/network/interfaces
echo "source /etc/network/interfaces.d/*.config" >> /etc/network/interfaces
 
# write eth and bond interfaces which are paired together in /etc/network/interfaces.d
rm -f /etc/network/interfaces.d/*
cat > /etc/network/interfaces.d/${BONDNAME}.config << EOL
 
# file generated by MAAS bondsetup script
 
auto ${INTERAFACE1}
iface ${INTERFACE1} inet manual
bond-master ${BONDNAME}
bond-primary ${INTERFACE1}
 
auto ${INTERFACE2}
iface ${INTERFACE2} inet manual
bond-master ${BONDNAME}
 
auto ${BONDNAME}
iface ${BONDNAME} inet manual
bond-mode balance-xor
bond-miimon 100
bond-slaves none
 
EOL


# check that bonding module is loaded into the kernel
for moduleName in loop bonding rtc lp ; do
  # if module not in list, add it
  if ! cat /etc/modules | grep "$moduleName" ; then
    echo "$moduleName" >> /etc/modules
  fi
done

